server:
  port: 8081
spring:
  application:
    name: user-management-service
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: testuser
    password: password
logging:
  level:
    org.springframework.data.r2dbc: Debug
---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:

---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/