server:
  port: ${PORT:8081}
spring:
  application:
    name: usermanagement-service
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 11b6d54ddbb4ad8a4c52
            clientSecret: cd0051d83b1594a3040ddbfe01602074cf4977e2
jwt.secret: javainuse
---
eureka:
  instance:
    hostname: hidden-tundra-10439.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
    non-secure-port: 80
    secure-port: 443
  client:
    serviceUrl:
      defaultZone: http://disc-service.herokuapp.com/eureka/
---
spring:
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:postgresql://ec2-52-54-212-232.compute-1.amazonaws.com:5432/d6tghft11usvrg
    username: zmyfbzaqkmvxoj
    password: 8091c7c8003390e13bd5093b069218221a7f54850a92850145e445175a30cb27
logging:
  level:
    org.springframework.data.r2dbc: Debug
---
#spring:
#  profiles: test
#  r2dbc:
#    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    name: sa
#    password: