server:
  port: 8081
spring:
  application:
    name: usermanagement-service
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 11b6d54ddbb4ad8a4c52
            clientSecret: cd0051d83b1594a3040ddbfe01602074cf4977e2
jwt.secret: javainuse
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/test
    username: postgres
    password: password
logging:
  level:
    org.springframework.data.r2dbc: Debug
---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    appname: ${spring.application.name}